[build]
publish = "public"
functions = "functions"

  [build.lifecycle]
  init = [
    "echo 'Starting the build'"
  ]
  build = [
    "echo 'hello world'"
  ]
  finally = [
    "echo 'Ending the build'"
  ]

[plugins]

  [plugins.debugPlugin]
  type = "./plugins/debug"
